version: '2'

services:
  apt-cacher-ng:
    restart: always
    container_name: apt-cacher-ng
    image: rajalokan/apt-cacher-ng
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
